version: '3.8'

services:
  # База данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-tasks}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Сервис аутентификации
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${AUTH_DB_NAME:-auth}
      JWT_SECRET: ${JWT_SECRET:-secret}
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  # Сервис задач
  task-service:
    build:
      context: ./task-service
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${TASK_DB_NAME:-tasks}
      JWT_SECRET: ${JWT_SECRET:-secret}
      AUTH_SERVICE_URL: "http://auth-service:8080"
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: