name: Go CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: ["auth-service", "task-service"]
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install dependencies for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: go mod tidy

      - name: Run tests for ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        timeout-minutes: 10
        run: go test -v ./...

      - name: Build ${{ matrix.service }}
        working-directory: ./${{ matrix.service }}
        run: go build -v ./cmd/...